---
name: Test-Prereq
version: 1.037_02
author:
  - 'brian d foy <bdfoy@cpan.org>'
abstract: Ensure a build file lists all pre-requisites
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::Builder: 0
  Test::Builder::Tester: 0
  Test::More: 0
  perl: 5.010
requires:
  Module::Build: 0
  Module::CoreList: 0
  Module::Info: 0
recommends:
  Test::Manifest: 2.00
configure_requires:
  Module::Build: 0.35
provides:
  Test::Prereq:
    file: lib/Prereq.pm
    version: 1.037_02
  Test::Prereq::Build:
    file: lib/Build.pm
    version: 1.037_02
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
