--- #YAML:1.0
name:               Test-Prereq
version:            1.037
abstract:           check if Makefile.PL has the right pre-requisites
author:
    - brian d foy <bdfoy@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Module::Build:        0
    Module::CoreList:     0
    Module::Info:         0
    Test::Builder:        0
    Test::Builder::Tester:  0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
