--- #YAML:1.0
name:                Test-Prereq
version:             1.034
abstract:            check if Makefile.PL has the right pre-requisites
license:             perl
author:              
    - brian d foy <bdfoy@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Module::Build:                 0
    Module::CoreList:              0
    Module::Info:                  0
    Test::Builder:                 0
    Test::Builder::Tester:         0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
