# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-Prereq
version:      1.027
version_from: lib/Prereq.pm
installdirs:  site
requires:
    Module::Build:                 0
    Module::CoreList:              0
    Module::Info:                  0
    Test::Builder:                 0
    Test::Builder::Tester:         0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.23
